# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutapp2018', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycletime',
            name='location',
            field=models.CharField(default='none', max_length=35),
        ),
    ]
