# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutapp2018', '0002_cycletime_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveIntegerField()),
                ('blue_one', models.PositiveIntegerField()),
                ('blue_two', models.PositiveIntegerField()),
                ('blue_three', models.PositiveIntegerField()),
                ('red_one', models.PositiveIntegerField()),
                ('red_two', models.PositiveIntegerField()),
                ('red_three', models.PositiveIntegerField()),
            ],
        ),
    ]
