# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutapp2018', '0003_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_position', models.CharField(choices=[('close', 'close'), ('middle', 'middle'), ('far', 'far')], max_length=10000)),
                ('cubes_in_switch', models.IntegerField()),
                ('cubes_in_scale', models.IntegerField()),
                ('cubes_in_vault', models.IntegerField()),
                ('cubes_dropped', models.IntegerField()),
            ],
        ),
    ]
