# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutapp2018', '0005_auto_20180228_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='blue_one_scout',
            field=models.CharField(default='none', max_length=35),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_three_scout',
            field=models.CharField(default='none', max_length=35),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_two_scout',
            field=models.CharField(default='none', max_length=35),
        ),
        migrations.AddField(
            model_name='match',
            name='red_one_scout',
            field=models.CharField(default='none', max_length=35),
        ),
        migrations.AddField(
            model_name='match',
            name='red_three_scout',
            field=models.CharField(default='none', max_length=35),
        ),
        migrations.AddField(
            model_name='match',
            name='red_two_scout',
            field=models.CharField(default='none', max_length=35),
        ),
    ]
