# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutapp2018', '0006_auto_20180228_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.IntegerField()),
                ('team', models.IntegerField()),
                ('on_platform', models.BooleanField()),
                ('climb_success', models.CharField(choices=[('succsessful', 'succsessful'), ('assisted', 'assisted'), ('levitated', 'levitated'), ('fell', 'fell'), ('DNA', 'DNA')], max_length=1000)),
                ('assist', models.CharField(choices=[('succsessfully carried two', 'succsessfully carried two'), ('succsessfully carried one', 'succsessfully carried one'), ('dropped a teammate', 'dropped a teammate'), ('DNA', 'DNA')], max_length=1000)),
            ],
        ),
    ]
