# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutapp2018', '0007_endgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='baseline_crossed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auto',
            name='starting_position',
            field=models.CharField(choices=[('left', 'left'), ('middle', 'middle'), ('right', 'right')], max_length=10000),
        ),
        migrations.AlterField(
            model_name='endgame',
            name='climb_success',
            field=models.CharField(choices=[('succsessful', 'succsessful'), ('carried by another team', 'carried by another team'), ('levitated', 'levitated'), ('fell', 'fell'), ('attempted but failed', 'attempted but failed'), ('DNA', 'DNA')], max_length=1000),
        ),
    ]
